### ISSUE TITLE
Private Data and Missing Files in load.rmd file

### ISSUE THREAD

**Issue by usr110** [npct/pct#13]
@Robinlovelace 
As the title says, we can't run the code unless we get access to the private-data folder - mentioned at https://github.com/npct/pct/edit/master/load.Rmd#L129

Also, the shape object, msoasmapshaped_25%.shp, mentioned at: 

https://github.com/npct/pct/edit/master/load.Rmd#L62

is not present in the pct-bigdata repo. Would be great if you resolve these issues.

**Comment by Robinlovelace** [comment]
Yes - sorry for the delay. Plan: Dropbox or Drive folder. Also sorry @audev for being slow on this.

**Comment by Robinlovelace** [comment]
@nikolai-b do you have any suggestions of 'best practice' from your experience on this?
