### ISSUE TITLE
List of local files

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct#3]
- [x] `~/Documents/Transport.bib` in [flow-model.Rmd](https://github.com/npct/pct/blob/master/documents/flow-model.Rmd)
- [x] `/home/robin/Dropbox/DfT bid/figures/las-gender-pcycle.png` in [flow-model.Rmd](https://github.com/npct/pct/blob/master/documents/flow-model.Rmd)
- [x] `/home/robin/Dropbox/DfT bid/Data analysis/Test_DD/TestPlanck_150303/150304_SegmentationCompare_8cat.xlsx` in [testing-dd-ffs.Rmd](https://github.com/npct/pct/blob/master/documents/testing-dd-ffs.Rmd) and [dd-paper.Rmd](https://github.com/npct/pct/blob/master/documents/dd-paper.Rmd)
- [x] `/media/robin/data/data-to-add/msoa-2011-sex-method-ttw-nomis-lc7103ew.csv` in [load-cents.R](https://github.com/npct/pct/blob/master/loading-data/load-cents.R)
- [x] `/media/robin/data/data/UKDA-5340-spss/spss/spss19/` in [pswitch-model-NTS.R](https://github.com/npct/pct)/blob/master/models/pswitch-model-NTS.R)
- [x] `/media/robin/data/data-to-add/public-flow-data-msoa/wu03ew_v2.csv` in a few (case-studies/manchester.R, case-studies/leeds-minitest.R, case-studies/leeds-wider.R, and case-studies/manchester.md)

and others.  If there are old files in here then let's get rid of them and clean it up.
I think we should aim to get no links to external files included.

**Comment by Robinlovelace** [comment]
:+1:

**Comment by Robinlovelace** [comment]
Done I think

**Comment by nikolai-b** [comment]
:+1: will check later and let you know if I find any strays :smile:
