### ISSUE TITLE
Add % by car variable

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct#6]
This is not a priority issue but would be a useful way to see the potential congestion benefit of cycling uptake in different areas.

**Comment by JDWoodcock** [comment]
hi Alvaro please prioritise work on this- if you can also solve % by foot at the same time that would be even better.

**Comment by audev** [comment]
Will have a look today.

Still I have the impression that the task also requires some info from Robin.

```
            Alvaro
```

**Comment by Robinlovelace** [comment]
Hi @audev if you need info, just ask!

**Comment by audev** [comment]
So I've cloned the repos, run load.Rmd. 
It can't find the files at L62  (shapefile, json files). I take these files are not needed for seeing %car trips, or are they?

**Comment by audev** [comment]
Added the %car use variable (this includes drivers and passengers). 
Minor change to ukmsoa so that scripts can be run (link reading from file msoas.shp as msoas.geojson was not available).

**Comment by JDWoodcock** [comment]
@audev great. Does it include % walking too?

**Comment by audev** [comment]
No, it doesn’t. I’ll add that.

**Comment by Robinlovelace** [comment]
:+1:

**Comment by JDWoodcock** [comment]
@audev reopened as walking not committed yet

**Comment by JDWoodcock** [comment]
@audev Alvaro I assume this means you done walking? If so great- that will be really useful for the HEAT calculation but please could you add a comment to confirm it when you close it.

**Comment by audev** [comment]
@JDWoodcock  Yes, it was added Monday itself, but the commit was pending. I thought it was self-explanatory. 
The scenarios bit may be more interesting in terms of comments and HEAT use....
